/**
 * Downloads the four typefaces the two design languages use into `public/fonts/`
 * and writes the `@font-face` block that names them.
 *
 * They are self-hosted rather than hot-linked because `http/headers.ts` sets a
 * strict CSP and the public pages must not depend on a third-party origin to
 * render — the same reason `live.js` and the stylesheets are served from here.
 *
 * Checked-in output, run by hand: `node scripts/fetch-fonts.mjs`. Nothing in the
 * build depends on it, so a font revision is a deliberate commit and not a
 * surprise in CI.
 *
 * Only `latin` and `latin-ext` are kept. Speaker names carry European
 * diacritics, which `latin` alone drops; the other seven subsets Google serves
 * are weight this product never renders.
 */

import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(ROOT, "public", "fonts");

/** A modern UA, or Google answers with `.ttf` and the files quadruple in size. */
const UA =
  "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36";

const KEEP = new Set(["latin", "latin-ext"]);

/**
 * The weights and axes each language actually asks for, from the handoff:
 * Public Sans 300–800 plus italic 400, JetBrains Mono 400–700, Source Serif 4
 * 300–700 plus italic, Karla 400–700.
 *
 * **Source Serif 4 ships without its optical-size axis, and that is a departure
 * from the handoff, taken on a measurement.** `opsz 8..60` costs 119.5 KiB for
 * the roman latin face against 19.6 KiB without it — six times the payload, on
 * the critical path of the one surface with a hard first-render budget (1.5 s
 * on a throttled mid-range phone). Measured on that profile the axis alone was
 * 866 ms of transfer. Optical sizing is a real refinement; it is not worth
 * two-thirds of the budget for a page whose largest type is a heading nobody
 * compares against a caption.
 */
const FAMILIES = [
  { file: "public-sans", query: "Public+Sans:ital,wght@0,300..800;1,400" },
  { file: "jetbrains-mono", query: "JetBrains+Mono:wght@400..700" },
  { file: "source-serif-4", query: "Source+Serif+4:ital,wght@0,300..700;1,400" },
  { file: "karla", query: "Karla:wght@400..700" },
];

/**
 * Google's CSS is one `@font-face` per subset, each preceded by a
 * `/* subset *\/` comment naming it. The comment is the only place the subset
 * appears, so it is parsed rather than inferred from the URL hash.
 */
function parseFaces(css) {
  const faces = [];
  const re = /\/\*\s*([a-z-]+)\s*\*\/\s*@font-face\s*\{([^}]+)\}/g;
  for (let m; (m = re.exec(css)); ) {
    const [, subset, block] = m;
    const url = /url\((https:\/\/[^)]+\.woff2)\)/.exec(block)?.[1];
    const range = /unicode-range:\s*([^;]+);/.exec(block)?.[1]?.trim();
    const style = /font-style:\s*([^;]+);/.exec(block)?.[1]?.trim() ?? "normal";
    const weight = /font-weight:\s*([^;]+);/.exec(block)?.[1]?.trim() ?? "400";
    const stretch = /font-stretch:\s*([^;]+);/.exec(block)?.[1]?.trim() ?? null;
    const family = /font-family:\s*'([^']+)'/.exec(block)?.[1] ?? "";
    if (url && range) faces.push({ subset, url, range, style, weight, stretch, family });
  }
  return faces;
}

async function main() {
  await mkdir(OUT, { recursive: true });
  const blocks = [];

  for (const family of FAMILIES) {
    const res = await fetch(`https://fonts.googleapis.com/css2?family=${family.query}&display=swap`, {
      headers: { "user-agent": UA },
    });
    if (!res.ok) throw new Error(`${family.query}: ${res.status}`);
    const faces = parseFaces(await res.text()).filter((f) => KEEP.has(f.subset));
    if (faces.length === 0) throw new Error(`${family.query}: no latin subset in the response`);

    for (const face of faces) {
      const italic = face.style.startsWith("italic") || face.style.startsWith("oblique");
      const name = `${family.file}${italic ? "-italic" : ""}-${face.subset}.woff2`;
      const bytes = new Uint8Array(await (await fetch(face.url, { headers: { "user-agent": UA } })).arrayBuffer());
      await writeFile(join(OUT, name), bytes);
      console.log(`${name}  ${(bytes.length / 1024).toFixed(1)} KiB`);
      blocks.push(
        [
          "@font-face {",
          `  font-family: "${face.family}";`,
          `  font-style: ${face.style};`,
          `  font-weight: ${face.weight};`,
          ...(face.stretch ? [`  font-stretch: ${face.stretch};`] : []),
          "  font-display: swap;",
          `  src: url("/fonts/${name}") format("woff2");`,
          `  unicode-range: ${face.range};`,
          "}",
        ].join("\n"),
      );
    }
  }

  const header = [
    "/* Generated by scripts/fetch-fonts.mjs. Do not edit by hand.",
    " *",
    " * Imported by both admin.css and portal.css. The two languages share no",
    " * typeface, but they do share this file rather than duplicating twelve",
    " * @font-face blocks — a browser that has loaded neither downloads only the",
    " * faces the page it is on actually uses.",
    " */",
    "",
  ].join("\n");
  await writeFile(join(OUT, "fonts.css"), `${header}\n${blocks.join("\n\n")}\n`);
  console.log(`\nfonts.css  ${blocks.length} faces`);
}

await main();
